name: Android CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout xpra-client repo (main)
        uses: actions/checkout@v3

      - name: Checkout bee-encode repo
        uses: actions/checkout@v3
        with:
          repository: GhettiGuru/bee-encode
          path: ../bee-encode
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout rencode4j repo
        uses: actions/checkout@v3
        with:
          repository: GhettiGuru/rencode4j
          path: ../rencode4j
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Decode keystore
        run: echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 -d > release.keystore

      - name: Cache Gradle
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle', '**/gradle.lockfile') }}

      - name: Build and publish rencode4j
        working-directory: ../rencode4j
        run: |
          ./gradlew build
          ./gradlew publishToMavenLocal

      - name: Build and publish bee-encode
        working-directory: ../bee-encode
        run: |
          ./gradlew build
          ./gradlew publishToMavenLocal

      - name: Build xpra-client (main project)
        env:
          KEYSTORE_FILE: release.keystore
          STORE_PASSWORD: ${{ secrets.KEYSTORE_PASS }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEYSTORE_PASS }}
        run: |
          ./gradlew build -PkeystoreFile=$KEYSTORE_FILE -PkeystorePassword=$STORE_PASSWORD -PkeyAlias=$KEY_ALIAS -PkeyPassword=$KEY_PASSWORD

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: app/build/outputs/apk/release/*.apk
