name: Android CI
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout main repo
    - name: Checkout xpra-client
      uses: actions/checkout@v3
      with:
        path: xpra-client

    # 2. Setup JDK 17
    - name: Setup JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 17

    # 3. Cache Gradle dependencies and wrapper
    - name: Cache Gradle
      uses: actions/cache@v3
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle', '**/gradle.lockfile') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    # 4. Install local JARs to Maven repo
    - name: Install local JARs to Maven repo
      run: |
        # bee-encode
        mkdir -p ~/.m2/repository/com/github/GhettiGuru/bee-encode/0.3/
        cp xpra-client/libs/bee-encode-0.3.jar ~/.m2/repository/com/github/GhettiGuru/bee-encode/0.3/bee-encode-0.3.jar
        cat > ~/.m2/repository/com/github/GhettiGuru/bee-encode/0.3/bee-encode-0.3.pom <<EOF
        <project>
          <modelVersion>4.0.0</modelVersion>
          <groupId>com.github.GhettiGuru</groupId>
          <artifactId>bee-encode</artifactId>
          <version>0.3</version>
        </project>
        EOF

        # rencode4j
        mkdir -p ~/.m2/repository/com/github/GhettiGuru/rencode4j/1.2.0/
        cp xpra-client/libs/rencode4j-1.2.0.jar ~/.m2/repository/com/github/GhettiGuru/rencode4j/1.2.0/rencode4j-1.2.0.jar
        cat > ~/.m2/repository/com/github/GhettiGuru/rencode4j/1.2.0/rencode4j-1.2.0.pom <<EOF
        <project>
          <modelVersion>4.0.0</modelVersion>
          <groupId>com.github.GhettiGuru</groupId>
          <artifactId>rencode4j</artifactId>
          <version>1.2.0</version>
        </project>
        EOF

    - name: Decode Keystore from secret
      run: |
          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 --decode > keystore.jks
          working-directory: xpra-client-android

    - name: Build APK Release - CompleteNormal
      run: ./gradlew assembleCompleteNormalRelease -PdisableAnalytics=true
      working-directory: xpra-client-android 
      env:
          KEYSTORE_PATH: ${{ github.workspace }}/island/keystore.jks
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}

    # 7. Upload the signed APK artifact
    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: release-apk
        path: xpra-client/app/build/outputs/apk/release/*.apk
