name: Android CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GRADLE_USER_HOME: ${{ runner.temp }}/.gradle

    steps:
      # Checkout main xpra-client repo
      - name: Checkout xpra-client
        uses: actions/checkout@v3
        with:
          path: xpra-client

      # Checkout rencode4j repo
      - name: Checkout rencode4j
        uses: actions/checkout@v3
        with:
          repository: GhettiGuru/rencode4j
          path: rencode4j
          token: ${{ secrets.GH_TOKEN }}

      # Checkout bee-encode repo
      - name: Checkout bee-encode
        uses: actions/checkout@v3
        with:
          repository: GhettiGuru/bee-encode
          path: bee-encode
          token: ${{ secrets.GH_TOKEN }}

      # Setup JDK 17
      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      # Cache Gradle dependencies to speed up builds
      - name: Cache Gradle
        uses: actions/cache@v3
        with:
          path: |
            ${{ runner.temp }}/.gradle/caches
            ${{ runner.temp }}/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle', '**/gradle.lockfile') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      # Decode Android signing keystore
      - name: Decode keystore
        run: echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 -d > release.keystore

      # Build and publish rencode4j locally
      - name: Build and publish rencode4j
        working-directory: ./rencode4j
        run: |
          ./gradlew clean build publishToMavenLocal

      # Build and publish bee-encode locally
      - name: Build and publish bee-encode
        working-directory: ./bee-encode
        run: |
          ./gradlew clean build publishToMavenLocal

      # Build xpra-client module using local Maven artifacts
      - name: Build xpra-client
        working-directory: ./xpra-client
        env:
          KEYSTORE_FILE: ../release.keystore
          STORE_PASSWORD: ${{ secrets.KEYSTORE_PASS }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
        run: |
          ./gradlew clean build \
            -PkeystoreFile=$KEYSTORE_FILE \
            -PkeystorePassword=$STORE_PASSWORD \
            -PkeyAlias=$KEY_ALIAS \
            -PkeyPassword=$KEY_PASSWORD

      # Upload the APK artifact
      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: xpra-client/app/build/outputs/apk/release/*.apk
